# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35cadb23c5c4a476dc7aae8e6cd7cffe6a5dca7f25477440e17914c5fab1fd3ac9ce812cdb8349bb819715b0f19762b4c55f8349c1f87cbb3f7fe021ddbb6465

test:
  secret_key_base: d6b59ff0bdb89c2e27762d05692876a1a58e07b1efe50c75f8a7b34db2eb371174c31659e28fe5957ba3a23874aa992d81f1fd2084500e9ae96baf71344146e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
